global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'teams'

receivers:
- name: 'teams'
  webhook_configs:
  - url: 'https://xtranetbpo.webhook.office.com/webhookb2/fe520c5d-7b15-4f2f-a3ac-c1d8eb6d7d8e@ffc09875-f21d-4a06-a4aa-8fd68133c6c2/IncomingWebhook/777e941036644e73bc80742509b42024/6c34b87d-f41d-4068-ba81-b1af74798edd/V2TPzTA8LY0KKpWUFU-iJ3IgkLjaduhzmWcjF-aJ4VLu01'
    send_resolved: true
