global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporters'
    static_configs:
      - targets:
        - '185.252.234.29:9100'
        labels:
          instance: 'server1'
      - targets:
        - '84.46.255.10:9100'
        labels:
          instance: 'server2'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.+|process_.+'
        action: drop
